[package]
name = "allogator"
version = "0.1.1"
edition = "2021"

[dependencies]
rawpointer = "0.2.1"
static_assertions = "1.1.0"
log = "0.4"

[dev-dependencies]
env_logger = "0.9"
rand = "0.8"

[features]
extra-checks = []
